### ISSUE TITLE
BTFU 1.9-1.4 requires 1.9 minecraft not 1.9.4

### ISSUE THREAD

**Issue by JohnC94** [alexbobp/BTFU#1] opened 2016-06-14 14:57 UTC
BTFU halts server startup

http://pastebin.com/qFAajC8t

**Comment by alexbobp** [comment] 2016-06-14 19:01
@JohnC94 Thank you very much for the report.  Someone else brought this issue to my attention too.  I built against the wrong forge version.  Please try the latest release, with 1.9.4 in the filename: http://minecraft.curseforge.com/projects/btfu/files/2307561

I think this fixes the issue but in all seriousness I appreciate the report.  I'm new to minecraft modding and it seems like a lot of people never bother to let me know if they have issues.  Please let me know if this release works.

**Comment by JohnC94** [comment] 2016-06-14 22:53
No worries, I'll give it a shot in a bit. Thank you for making this mod. :)

**Comment by JohnC94** [comment] 2016-06-14 23:15
I tried BTFU-1.9.4-1.4 and got this crash log, seems to be the same issue?

http://pastebin.com/FGvtwMpn

**Comment by JohnC94** [comment] 2016-06-15 05:28
@alexbobp  I tried BTFU-1.9.4-1.4 and got this crash log, seems to be the same issue?

http://pastebin.com/FGvtwMpn

**Comment by alexbobp** [comment] 2016-06-15 05:50
In that log it still shows the filename BTFU-1.9-1.4.jar.  Are you sure you removed the old version?

**Comment by JohnC94** [comment] 2016-06-15 15:54
Yes, I just tried again and got the same result. It shows the wrong file name in the crash log.

[Mod Folder](http://i.imgur.com/6xCfUus.png)

[New Crash Log](http://pastebin.com/4TZhHBwE)

**Comment by alexbobp** [comment] 2016-06-15 15:57
Strange.  so on line 23 of your log: "C:\Servers\Fractured\mods\BTFU-1.9-1.4.jar"
That's a file path that does not exist?  (I'm not trying to doubt you, just want to double-check)
As far as I know forge just shows actual filenames there so I am honestly confused.

By the way I want to give you a heads up, I did not write this mod for windows.  To get it to work on windows I highly recommend you install cygwin with the rsync package so that BTFU has unix-style rsync, cp, and rm commands available.  It's probably possible to do it without cygwin and I did leave the system commands configurable so people can try.

**Comment by JohnC94** [comment] 2016-06-15 16:09
"C:\Servers\Fractured\mods" exists but there is no "BTFU-1.9-1.4.jar"

**Comment by alexbobp** [comment] 2016-06-15 16:15
Man.  I hate to send you on a wild goose chase but this is really confusing, so humor me if you will... try renaming some of the other mod files in that folder as a test, and see if you see their old or new filenames in the forge crash log when you try running it again.

Or try removing BTFU entirely and starting up the server, then shutting it down and adding just the 1.9.4 version.

**Comment by alexbobp** [comment] 2016-06-17 15:05
if you can't respond I'm going to have to close this as an issue I can't reproduce.  but I'll still try to help if I can.

**Closed** 2016-06-17 16:23 UTC
